### PR TITLE
Sync k8snetworkplumbingwg/sriov-cni 20221128

### PR DESCRIPTION
**Pull request by cgoncalves**

### CODE REVIEW

**Comment by bn222** [comment]
The order is a bit weird compared to upstream. Can you reorder the commits?

**Comment by cgoncalves** [comment]
What exactly looks weird in the order of the commits?

```
$ git --no-pager log --cherry-pick --format="%h %s" --left-only --no-merges upstream/master...origin/master
3669d1f1 Retry setting VF MAC address
e92d0776 Reset the VF if failure occurs before the netconf is cached
2aea1bb5 Add pci address lock for allocated devices (#220)
02fe3503 bump cni&cni-plugins for support add ecmp route
db57cbad bump golang to 1.19
ba420ed4 Bump golang 1.18 and k8s 1.24 (#209)
48130211 Remove travis for build, test & deploy of container images
c0fdaf0d Fix docker files after hadolint check
002e8591 Use latest image version v2.3 in daemon templates
764b0160 Change daemonset imagePullPolicy from Never to IfNotPreset
2aa9b0e7 add daemonset spec for k8s v1.16 (#109)
```

The go mod vendor is because of 82a345aec264418d9e0c78c90952a4818d46f090

**Comment by bn222** [comment]
ok, thanks for clearing that up. /lgtm

**Comment by bn222** [comment]
I prefer we split this sync up to be "general sync stuff" + a PR that specifically fixes OCPBUGS-701.

**Comment by cgoncalves** [comment]
> I prefer we split this sync up to be "general sync stuff" + a PR that specifically fixes OCPBUGS-701.

Done

**Comment by cgoncalves** [comment]
> I prefer we split this sync up to be "general sync stuff" + a PR that specifically fixes OCPBUGS-701.

Following your logic, we would end up with 3 PRs:
- a sync PR that would only include one commit: db57cbad
- a PR to fix OCPBUGS-701
- a PR to fix OCPBUGS-3057

Please let me know what you want and I will make it happen.

**Comment by SchSeba** [comment]
I am fine with this PR to bump golang 1.19.
we can create others for the bug fix so it will be easy to request cherry-picks from the bot.
we can't cherry-pick this one as ocp 4.11 use 1.18

**Comment by bn222** [comment]
yes, that sounds good. thanks!

**Pull request merged**
