### PR TITLE
Update go.in/yaml

### PR DESCRIPTION
**Pull request by vrindle**

### CODE REVIEW

**Comment by SalDaniele** [comment]
@vrindle Please update PR title to correctly reference the OCPBUG in Jira (i.e. [4.12-PR](https://github.com/openshift/sriov-cni/pull/66#:~:text=%5Brelease%2D4.12%5D-,OCPBUGS%2D6572,-%3A%20bump%20gopkg.in)).

**Comment by bn222** [comment]
@vrindle ptal. Needs rebase and ptal at Sal's comment.

Also, @SchSeba shouldn't this be part of a sync?

**Comment by SalDaniele** [comment]
I believe we can close this PR, this issue was already fixed here: https://github.com/openshift/sriov-cni/pull/69

**Pull request closed without merging**
