### PR TITLE
4.8 update 20210309

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by SchSeba** [comment]
there is a problem building the container @zshi-redhat can you please take a look?

```
STEP 2: ENV "BUILD_LOGLEVEL"="0"
STEP 3: COPY . /usr/src/sriov-cni
STEP 4: WORKDIR /usr/src/sriov-cni
STEP 5: RUN make clean &&     make build
Setting GOPATH...
Cleaning...
Setting GOPATH...
Creating build directory...
main.go:8:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/containernetworking/cni/pkg/skel
main.go:9:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/containernetworking/cni/pkg/types
main.go:10:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/containernetworking/cni/pkg/types/current
main.go:11:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/containernetworking/cni/pkg/version
main.go:12:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/containernetworking/plugins/pkg/ipam
main.go:13:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/containernetworking/plugins/pkg/ns
../../pkg/utils/utils.go:12:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/redhat-virtio-net/govdpa/pkg/kvdpa
../../pkg/types/types.go:5:2: cannot find package "." in:
	/usr/src/sriov-cni/.gopath/src/github.com/k8snetworkplumbingwg/sriov-cni/vendor/github.com/vishvananda/netlink
make: *** [Makefile:59: /usr/src/sriov-cni/build/sriov] Error 1
STEP 6: FROM image-registry.openshift-image-registry.svc:5000/ci-op-wrzwip5v/pipeline@sha256:d43ae2d2dda3b60cb117f0fb16b63e754c01a7ff68ae53c655e361cfcbb1d43a
```

**Comment by zshi-redhat** [comment]
> there is a problem building the container @zshi-redhat can you please take a look?
> 
Thanks @SchSeba ! Fixed the building issue.

**Pull request merged**
