### PR TITLE
NHE-1: Add feature "Announce IP on pod creation"

### PR DESCRIPTION
**Pull request by wizhaoredhat**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@SchSeba Ping, you might be interested in this PR =)

**Comment by wizhaoredhat** [comment]
@bn222 @zshi-redhat Can anyone help with moving this PR forward?

**Comment by wizhaoredhat** [comment]
@bn222 I think approvers can only run the retest.

**Comment by wizhaoredhat** [comment]
Passes for me. Not sure why the CI is having issues.
```
[wizhao@fedora sriov-cni]$ sudo podman build -t sriov-cni-image -f ./Dockerfile .
[sudo] password for wizhao: 
[1/2] STEP 1/6: FROM golang:alpine AS builder
Resolved "golang" as an alias (/var/cache/containers/short-name-aliases.conf)
Trying to pull docker.io/library/golang:alpine...
Getting image source signatures
Copying blob 601c7710d0ea done  
Copying blob 5299e6f78605 skipped: already exists  
Copying blob 6569e6eb40cd done  
Copying blob 1cab0e43db0a skipped: already exists  
Copying blob 213ec9aee27d skipped: already exists  
Copying config 5dd973625d done  
Writing manifest to image destination
Storing signatures
[1/2] STEP 2/6: COPY . /usr/src/sriov-cni
--> 2c43a5a8ae7
[1/2] STEP 3/6: ENV HTTP_PROXY $http_proxy
--> d4dce6d942d
[1/2] STEP 4/6: ENV HTTPS_PROXY $https_proxy
--> 20c17fcda3a
[1/2] STEP 5/6: WORKDIR /usr/src/sriov-cni
--> 01953eb3086
[1/2] STEP 6/6: RUN apk add --no-cache --virtual build-dependencies build-base=~0.5 &&     make clean &&     make build
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/20) Installing libgcc (11.2.1_git20220219-r2)
(2/20) Installing libstdc++ (11.2.1_git20220219-r2)
(3/20) Installing binutils (2.38-r3)
(4/20) Installing libmagic (5.41-r0)
(5/20) Installing file (5.41-r0)
(6/20) Installing libgomp (11.2.1_git20220219-r2)
(7/20) Installing libatomic (11.2.1_git20220219-r2)
(8/20) Installing gmp (6.2.1-r2)
(9/20) Installing isl22 (0.22-r0)
(10/20) Installing mpfr4 (4.1.0-r0)
(11/20) Installing mpc1 (1.2.1-r0)
(12/20) Installing gcc (11.2.1_git20220219-r2)
(13/20) Installing musl-dev (1.2.3-r0)
(14/20) Installing libc-dev (0.7.2-r3)
(15/20) Installing g++ (11.2.1_git20220219-r2)
(16/20) Installing make (4.3-r0)
(17/20) Installing fortify-headers (1.1-r1)
(18/20) Installing patch (2.7.6-r7)
(19/20) Installing build-base (0.5-r3)
(20/20) Installing build-dependencies (20220913.140906)
Executing busybox-1.35.0-r17.trigger
OK: 187 MiB in 35 packages
Setting GOPATH...
Cleaning...
Setting GOPATH...
Creating build directory...
golang.org/x/sys/internal/unsafeheader
golang.org/x/net/internal/iana
github.com/containernetworking/plugins/pkg/utils/sysctl
golang.org/x/sys/unix
github.com/vishvananda/netns
github.com/safchain/ethtool
golang.org/x/net/bpf
net
github.com/containernetworking/plugins/pkg/ns
github.com/containernetworking/cni/pkg/types
github.com/containernetworking/plugins/pkg/utils/hwaddr
github.com/coreos/go-iptables/iptables
golang.org/x/net/internal/socket
github.com/vishvananda/netlink/nl
github.com/containernetworking/cni/pkg/utils
github.com/containernetworking/cni/pkg/types/020
github.com/containernetworking/cni/pkg/types/current
github.com/containernetworking/cni/pkg/version
golang.org/x/net/ipv6
golang.org/x/net/ipv4
github.com/containernetworking/cni/pkg/skel
github.com/containernetworking/cni/pkg/invoke
github.com/vishvananda/netlink
golang.org/x/net/icmp
github.com/k8snetworkplumbingwg/sriov-cni/pkg/types
github.com/containernetworking/plugins/pkg/ip
github.com/k8snetworkplumbingwg/sriov-cni/pkg/utils
github.com/containernetworking/plugins/pkg/ipam
github.com/k8snetworkplumbingwg/sriov-cni/pkg/config
github.com/k8snetworkplumbingwg/sriov-cni/pkg/sriov
github.com/k8snetworkplumbingwg/sriov-cni/cmd/sriov
Building sriov...
Done!
--> 0822bdcfd84
[2/2] STEP 1/6: FROM alpine:3
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:3...
Getting image source signatures
Copying blob 213ec9aee27d skipped: already exists  
Copying config 9c6f072447 done  
Writing manifest to image destination
Storing signatures
[2/2] STEP 2/6: COPY --from=builder /usr/src/sriov-cni/build/sriov /usr/bin/
--> 57a45779173
[2/2] STEP 3/6: WORKDIR /
--> a0763c111e9
[2/2] STEP 4/6: LABEL io.k8s.display-name="SR-IOV CNI"
--> 87a94f31868
[2/2] STEP 5/6: COPY ./images/entrypoint.sh /
--> 99b72f72d60
[2/2] STEP 6/6: ENTRYPOINT ["/entrypoint.sh"]
[2/2] COMMIT sriov-cni-image
--> b3dcde0f915
Successfully tagged localhost/sriov-cni-image:latest
b3dcde0f9150e1e649d618a9042dc957a8b21c65a288512fd74bca1094a0af36
```

**Comment by bn222** [comment]
@wizhaoredhat Would prefer if we can add `go mod vendor` as a pre-build step or something in the ci. Just to avoid having to commit all the dependencies.

**Comment by wizhaoredhat** [comment]
@zshi-redhat @bn222 Please approve and merge this. CI seems to be passing.

**Comment by zshi-redhat** [comment]
We'd prefer to do full sync to upstream before dev complete, this PR happens to contain upstream changes.

/lgtm

**Pull request merged**
