### PR TITLE
d/s only - build for RHEL8 and RHEL9

### PR DESCRIPTION
**Pull request by zeeke**
During upgrades, it can happen that the newer version of the CNI plugin, which is built on RHEL9, run on a RHEL8 system. As the `CGO_ENABLED` is forced to 1 due to the FIPS compliance, these situations lead to a `GLIBC_2.32' not found ...`
 error.

Make `Dockerfile.rhel` build binaries for both RHEL8 and RHEL9 Change default source path of `images/entrypoint.sh` to deploy the right build of the binary, based on the `/host/etc/os-release` file, if present.

### CODE REVIEW

**Review by SchSeba — COMMENTED** [review]
LGTM

lets wait for the non sleep from u/s work and then we can add this

**Comment by thom311** [comment]
@zeeke why was it not possible to compile the go binary only against rhel8? Shouldn't glibc be backward compatible, so that the binary build on rhel8 also runs on rhel9?

**Comment by thom311** [comment]
> @zeeke why was it not possible to compile the go binary only against rhel8? Shouldn't glibc be backward compatible, so that the binary build on rhel8 also runs on rhel9?

there is [this comment on OCPBUGS-26220](https://issues.redhat.com/browse/OCPBUGS-26220?focusedId=23768668&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23768668)... but I don't think this answers it (does it?)

**Comment by zeeke** [comment]
hi @thom311 , I proceeded this way as per this doc comment
https://docs.google.com/document/d/1N8KyDY7KmgUYA9EOtDDQolebz0qi3nhT20IOn4D-xS4/edit?disco=AAAAZEp3mP8

"Sounds like" all the RHEL9 binaries should be built on RHEL9 because of FIPS reasons. However, nobody had said that explicitly, but I assumed that was true, as the same logic has been applied to OVN and multus.

**Pull request merged**
