### PR TITLE
OCPBUGS-26220: [release-4.15] build for RHEL8 and RHEL9

### PR DESCRIPTION
**Pull request by zeeke**
cherrypick of
- https://github.com/openshift/sriov-cni/pull/97
- https://github.com/openshift/sriov-cni/commit/c9c49b551e9e9acdb034566703ab6b0a9c180c63

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@zeeke I thought the initcontainer would not use entrypoint.sh but rather would just do the copy as a shell command?

**Comment by zeeke** [comment]
> @zeeke I thought the initcontainer would not use entrypoint.sh but rather would just do the copy as a shell command?

The initcontainer in the sriov-network-operator deployment was doing a simple copy before
- https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/581

(brought downstream in 4.16 [here](https://github.com/openshift/sriov-network-operator/pull/887), [4.15 backport PR](https://github.com/openshift/sriov-network-operator/pull/893))

What we are trying to achieve here is the same logic as we have in multus
- https://github.com/openshift/cluster-network-operator/blob/873b3290a2de28fb7fb41ad498fc9872dcb1a93b/bindata/network/multus/multus.yaml#L13

**Comment by zeeke** [comment]
/jira refresh

@wizhaoredhat @SchSeba please take a look

**Comment by wizhaoredhat** [comment]
> > @zeeke I thought the initcontainer would not use entrypoint.sh but rather would just do the copy as a shell command?
> 
> The initcontainer in the sriov-network-operator deployment was doing a simple copy before
> 
> * [Use default `{ib-}sriov-cni` entrypoint script k8snetworkplumbingwg/sriov-network-operator#581](https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/581)
> 
> (brought downstream in 4.16 [here](https://github.com/openshift/sriov-network-operator/pull/887), [4.15 backport PR](https://github.com/openshift/sriov-network-operator/pull/893))
> 
> What we are trying to achieve here is the same logic as we have in multus
> 
> * https://github.com/openshift/cluster-network-operator/blob/873b3290a2de28fb7fb41ad498fc9872dcb1a93b/bindata/network/multus/multus.yaml#L13

What was wrong with "            - /bin/sh
            - -c
            - cp /usr/bin/sriov /host/opt/cni/bin/" in the pod spec? 
            
            Is it because CNI's built from different RHEL (8 vs 9) bases are incompatible?

**Comment by zeeke** [comment]
> /label backport-risk-assessed

thanks @wizhaoredhat . It looks like your username is missing in 

https://github.com/openshift/release/blob/390c15f13c0e943ec89e1ff0535259ae95d030c5/core-services/prow/02_config/openshift/sriov-cni/_pluginconfig.yaml#L4-L12

@SchSeba @bn222 can you take a look a provide `backport-risk-assessed` if ok?

@evgenLevin @zhaozhanqi I'll need `cherry-pick-approved` as well. Please, take a look

**Pull request merged**
