### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by wizhaoredhat**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@zshi-redhat Please review.

**Comment by wizhaoredhat** [comment]
@SchSeba Could you please merge this?

**Comment by wizhaoredhat** [comment]
@bn222 Could you merge this?

**Comment by bn222** [comment]
@wizhaoredhat The bot is complaining that the OWNERS file has an invalid format. Can you figure out what's wrong with it?

**Comment by wizhaoredhat** [comment]
@bn222 @zshi-redhat Please review and merge. I think the blocker was removed.

**Pull request merged**
