### PR TITLE
OCPBUGS-4602: Retry setting VF MAC address

### PR DESCRIPTION
**Pull request by cgoncalves**
Backport of https://github.com/openshift/sriov-cni/pull/53

### CODE REVIEW

**Comment by cgoncalves** [comment]
@zshi-redhat Could you please provide backport-risk-assessed label?

**Comment by bn222** [comment]
@zhaozhanqi

**Comment by cgoncalves** [comment]
OCP 4.11 backport here: https://github.com/openshift/sriov-cni/pull/59

**Pull request merged**
